#!/usr/bin/env python3
"""Convert a 4x4 generated character sheet to Muse's RGB565 frame format."""
from pathlib import Path
import argparse
from PIL import Image

ap=argparse.ArgumentParser(description=__doc__)
ap.add_argument('character',choices=['oyster'])
args=ap.parse_args()
folder=Path(__file__).resolve().parent/args.character
source=Image.open(folder/'source.png').convert('RGB')
frames=[]
for i in range(16):
    x,y=i%4,i//4
    sprite=source.crop((round(x*source.width/4),round(y*source.height/4),
                        round((x+1)*source.width/4),round((y+1)*source.height/4)))
    sprite=sprite.resize((64,64),Image.Resampling.LANCZOS)
    frames.append([((r>>3)<<11)|((g>>2)<<5)|(b>>3) for r,g,b in sprite.get_flattened_data()])
with (folder/'sprites.h').open('w') as out:
    out.write('/* Generated by avatar/pack_sprites.py from source.png. */\n')
    out.write(f'static const uint16_t {args.character.replace("-","_")}_sprites[16][4096] = {{\n')
    for frame in frames:
        out.write('{\n')
        for j in range(0,len(frame),32):out.write(','.join(f'0x{x:04x}' for x in frame[j:j+32])+',\n')
        out.write('},\n')
    out.write('};\n')
print(f'Packed {args.character}: 16 frames, 128 KiB.')
